// Reproducibility capsule.
//
// The JSON snapshot alone captures the *specification* of an experiment — the
// architecture and the hyperparameters — but not the run: no seeds, no library
// versions, no dataset identity, no hardware. This module packages the
// specification together with everything needed to re-execute it, and is honest
// in the accompanying notes about what remains outside its control.
//
// The ZIP is written here rather than with a library, because the tool ships as
// a static bundle with no build step and no runtime dependencies, and adding one
// for this would undo that.

// Versions this generator targets and has been tested against. The exported
// script additionally records the versions actually resolved at run time, which
// is the only reliable account of what produced a given result.
export const TARGET_VERSIONS = {
    python: '3.11',
    tensorflow: '2.21.0',
    numpy: '2.1.3',
    'scikit-learn': '1.6.1',
    xgboost: '2.1.3'
};

// --- minimal ZIP (store, no compression) -----------------------------------
const CRC_TABLE = (() => {
    const t = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
        let c = n;
        for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1;
        t[n] = c >>> 0;
    }
    return t;
})();

function crc32(bytes) {
    let c = 0xFFFFFFFF;
    for (let i = 0; i < bytes.length; i++) c = CRC_TABLE[(c ^ bytes[i]) & 0xFF] ^ (c >>> 8);
    return (c ^ 0xFFFFFFFF) >>> 0;
}

function dosTime(d) {
    return [
        ((d.getHours() << 11) | (d.getMinutes() << 5) | (d.getSeconds() / 2)) & 0xFFFF,
        (((d.getFullYear() - 1980) << 9) | ((d.getMonth() + 1) << 5) | d.getDate()) & 0xFFFF
    ];
}

export function makeZip(files, when = new Date()) {
    const enc = new TextEncoder();
    const [time, date] = dosTime(when);
    const locals = [];
    const centrals = [];
    let offset = 0;

    for (const { name, content } of files) {
        const nameBytes = enc.encode(name);
        const data = enc.encode(content);
        const crc = crc32(data);

        const local = new DataView(new ArrayBuffer(30));
        local.setUint32(0, 0x04034b50, true);
        local.setUint16(4, 20, true);          // version needed
        local.setUint16(6, 0, true);           // flags
        local.setUint16(8, 0, true);           // method: stored
        local.setUint16(10, time, true);
        local.setUint16(12, date, true);
        local.setUint32(14, crc, true);
        local.setUint32(18, data.length, true);
        local.setUint32(22, data.length, true);
        local.setUint16(26, nameBytes.length, true);
        local.setUint16(28, 0, true);
        locals.push(new Uint8Array(local.buffer), nameBytes, data);

        const central = new DataView(new ArrayBuffer(46));
        central.setUint32(0, 0x02014b50, true);
        central.setUint16(4, 20, true);
        central.setUint16(6, 20, true);
        central.setUint16(8, 0, true);
        central.setUint16(10, 0, true);
        central.setUint16(12, time, true);
        central.setUint16(14, date, true);
        central.setUint32(16, crc, true);
        central.setUint32(20, data.length, true);
        central.setUint32(24, data.length, true);
        central.setUint16(28, nameBytes.length, true);
        central.setUint32(42, offset, true);
        centrals.push(new Uint8Array(central.buffer), nameBytes);

        offset += 30 + nameBytes.length + data.length;
    }

    const centralSize = centrals.reduce((n, p) => n + p.length, 0);
    const end = new DataView(new ArrayBuffer(22));
    end.setUint32(0, 0x06054b50, true);
    end.setUint16(8, files.length, true);
    end.setUint16(10, files.length, true);
    end.setUint32(12, centralSize, true);
    end.setUint32(16, offset, true);

    return new Blob([...locals, ...centrals, new Uint8Array(end.buffer)], { type: 'application/zip' });
}

// --- capsule contents -------------------------------------------------------
export function requirementsTxt(needsSklearn, needsXgboost) {
    const lines = [
        '# Versions this capsule was generated against.',
        '# The exported script also writes environment_lock.txt at run time with',
        '# the versions actually resolved, which is the authoritative record.',
        `numpy==${TARGET_VERSIONS.numpy}`
    ];
    if (needsSklearn) lines.push(`scikit-learn==${TARGET_VERSIONS['scikit-learn']}`);
    else lines.push(`tensorflow==${TARGET_VERSIONS.tensorflow}`);
    if (needsXgboost) lines.push(`xgboost==${TARGET_VERSIONS.xgboost}`);
    return lines.join('\n') + '\n';
}

export function environmentMd(config, seed) {
    return `# Environment

Generated by Layernaut Studio ${config.toolVersion} on ${config.exportedAt}.

## What this capsule pins

- The random seed (\`${seed}\`) for Python, NumPy${config.modelMode === 'ml' ? '' : ' and TensorFlow'}.
- The library versions the code was generated against (\`requirements.txt\`).
- The full experiment specification (\`config.json\`), which re-imports into the
  tool to reproduce the design itself.
- \`PYTHONHASHSEED\`, set before any hashing occurs.

## What it cannot pin, and why

Seeding constrains but does not eliminate run-to-run variation:

- **GPU kernels.** cuDNN selects algorithms at run time, and some reductions
  accumulate in non-deterministic order. Two runs on the same GPU can differ in
  the last few decimal places, and results will differ more across GPU models.
- **Hardware and thread count.** Floating-point addition is not associative, so
  a different number of threads can change the result.
- **The dataset.** The capsule records the dataset identifier and split
  parameters, not the data. Reproducing a run requires the same data.

**Bitwise reproduction across machines is therefore not claimed.** What the
capsule delivers is a portable, complete and re-executable specification, and a
record of the environment sufficient to explain a discrepancy when one appears.

For stricter determinism on a single machine, set
\`TF_DETERMINISTIC_OPS=1\` and \`TF_CUDNN_DETERMINISTIC=1\` before running, and
expect a performance cost.

## Recorded at run time

Executing \`train.py\` writes \`environment_lock.txt\` containing the resolved
package versions, the Python build, the platform and the visible devices.
`;
}

export function capsuleReadme(config) {
    return `# Reproducibility capsule

Experiment specification and everything needed to re-execute it.

| File | Purpose |
|---|---|
| \`train.py\` | Training script, seeded |
| \`notebook.ipynb\` | The same pipeline as a Colab notebook |
| \`config.json\` | Full specification; re-imports into Layernaut Studio |
| \`requirements.txt\` | Library versions the code was generated against |
| \`ENVIRONMENT.md\` | What is pinned, and what cannot be |

## Reproduce

    python -m venv .venv && source .venv/bin/activate
    pip install -r requirements.txt
    # edit the DATA section of train.py to point at your dataset
    python train.py

\`train.py\` writes \`environment_lock.txt\` recording the environment it actually
ran in. Keep it alongside your results.

## Specification

- Tool version: ${config.toolVersion}
- Schema version: ${config.schemaVersion}
- Exported: ${config.exportedAt}
- Model: ${config.model || 'custom'} (${config.modelMode})
- Seed: ${config.seed}
`;
}
